### ISSUE TITLE
Documentation : com.intellij.psi.impl.compiled.ClsMethodImpl cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by fharms** [davsclaus/camel-idea-plugin#208]
Press ctrl-q throw an error

>exchange = template.<caret>request("http://localhost:"+SERVICE_PORT+"/rest/myservice" + user);

```java
com.intellij.psi.impl.compiled.ClsMethodImpl cannot be cast to java.lang.String
java.lang.ClassCastException: com.intellij.psi.impl.compiled.ClsMethodImpl cannot be cast to java.lang.String
	at org.apache.camel.idea.documentation.CamelDocumentationProvider.getDocumentationElementForLookupItem(CamelDocumentationProvider.java:163)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.getDocumentationElementForLookupItem(CompositeDocumentationProvider.java:156)
	at com.intellij.codeInsight.documentation.DocumentationManager.getElementFromLookup(DocumentationManager.java:645)
	at com.intellij.codeInsight.documentation.DocumentationManager.a(DocumentationManager.java:588)
	at com.intellij.codeInsight.documentation.DocumentationManager.findTargetElement(DocumentationManager.java:573)
	at com.intellij.codeInsight.documentation.DocumentationManager.findTargetElement(DocumentationManager.java:567)
	at com.intellij.codeInsight.documentation.DocumentationManager.findTargetElement(DocumentationManager.java:394)
	at com.intellij.codeInsight.documentation.DocumentationManager.showJavaDocInfo(DocumentationManager.java:335)
	at com.intellij.codeInsight.documentation.DocumentationManager.showJavaDocInfo(DocumentationManager.java:311)
	at com.intellij.codeInsight.documentation.actions.ShowQuickDocInfoAction$1.invoke(ShowQuickDocInfoAction.java:52)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$null$0(CodeInsightAction.java:64)
	at com.intellij.codeInsight.actions.CodeInsightAction$$Lambda$2080/1341140682.run(Unknown Source)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$actionPerformedImpl$1(CodeInsightAction.java:70)
	at com.intellij.codeInsight.actions.CodeInsightAction$$Lambda$2079/77499830.run(Unknown Source)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformedImpl(CodeInsightAction.java:60)
	at com.intellij.codeInsight.documentation.actions.ShowQuickDocInfoAction.actionPerformed(ShowQuickDocInfoAction.java:108)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:199)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:91)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:159)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:213)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:634)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$$Lambda$1379/1124151106.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:204)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:477)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:657)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by mcollovati** [comment]
Same error occurs also on non Camel related classes (eg: quick dock for String methods)

**Comment by davsclaus** [comment]
Where do you position the cursor?

**Comment by fharms** [comment]
exchange = template.re<caret>quest("http://localhost:"+SERVICE_PORT+"/rest/myservice" + user);

**Comment by davsclaus** [comment]
I cannot reproduce it on master code, but I can see from the stacktrace about the type cast, so I have added a check a NPE check

**Comment by mcollovati** [comment]
Additional information to reproduce the problem

1. With the cursor on a method press CTRL+Space to get completion list
1. With a method from completion list highlighted press CTRL+Q

**Comment by davsclaus** [comment]
Thanks @mcollovati for the steps, then the current fix needs a bit more love to check the type as it relies on a toString repsentation which is not what we want, we should check its our psi element which we create for the completion list.
