### ISSUE TITLE
NullPointerException in CamelDocumentationProvider

### ISSUE THREAD

**Issue by Magamir** [davsclaus/camel-idea-plugin#247]
I received the following Exception while committing changes via git - so no intentionally interaction with the Camel plugin.

See the stacktrace for details:
`java.lang.NullPointerException
	at org.apache.camel.idea.documentation.CamelDocumentationProvider.getCustomDocumentationElement(CamelDocumentationProvider.java:233)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.getCustomDocumentationElement(CompositeDocumentationProvider.java:259)
	at com.intellij.codeInsight.documentation.DocumentationManager.a(DocumentationManager.java:592)
	at com.intellij.codeInsight.documentation.DocumentationManager.findTargetElement(DocumentationManager.java:573)
	at com.intellij.codeInsight.documentation.DocumentationManager.findTargetElement(DocumentationManager.java:567)
	at com.intellij.codeInsight.documentation.DocumentationManager.findTargetElement(DocumentationManager.java:394)
	at com.intellij.codeInsight.documentation.DocumentationManager.showJavaDocInfo(DocumentationManager.java:335)
	at com.intellij.codeInsight.documentation.DocumentationManager.doUpdateComponent(DocumentationManager.java:1036)
	at com.intellij.codeInsight.documentation.DockablePopupManager.a(DockablePopupManager.java:223)
	at com.intellij.psi.impl.PsiDocumentManagerBase$9$1.run(PsiDocumentManagerBase.java:583)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by davsclaus** [comment]
What version of the IDEA Camel plugin are you using?

**Comment by Magamir** [comment]
Version 0.3.6 - I updated this morning.
