### ISSUE TITLE
IndexNotReadyException

### ISSUE THREAD

**Issue by ignatov** [davsclaus/camel-idea-plugin#288]
Product: IDEA 171.3224  
OS: Windows 7   
Java: JetBrains s.r.o 1.8.0_112-release   

Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation

```
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:720)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:669)
	at com.intellij.util.indexing.FileBasedIndexImpl.processExceptions(FileBasedIndexImpl.java:838)
	at com.intellij.util.indexing.FileBasedIndexImpl.collectFileIdsContainingAllKeys(FileBasedIndexImpl.java:1072)
	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAllKeys(FileBasedIndexImpl.java:932)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.lambda$processFilesContainingAllKeys$20(PsiSearchHelperImpl.java:958)
	at com.intellij.openapi.project.DumbService$1.run(DumbService.java:95)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:125)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:92)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processFilesContainingAllKeys(PsiSearchHelperImpl.java:957)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processFilesWithText(PsiSearchHelperImpl.java:453)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.getFilesWithText(PsiSearchHelperImpl.java:436)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processElementsWithTextInGlobalScope(PsiSearchHelperImpl.java:272)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.bulkProcessElementsWithWord(PsiSearchHelperImpl.java:183)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processElementsWithWord(PsiSearchHelperImpl.java:164)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processElementsWithWord(PsiSearchHelperImpl.java:143)
	at com.intellij.psi.impl.search.PsiSearchHelperImpl.processElementsWithWord(PsiSearchHelperImpl.java:129)
	at org.apache.camel.idea.gutter.CamelRouteLineMarkerProvider.findRouteDestinationForPsiElement(CamelRouteLineMarkerProvider.java:172)
	at org.apache.camel.idea.gutter.CamelRouteLineMarkerProvider.collectNavigationMarkers(CamelRouteLineMarkerProvider.java:92)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectNavigationMarkers(RelatedItemLineMarkerProvider.java:49)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectSlowLineMarkers(RelatedItemLineMarkerProvider.java:40)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:209)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:111)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:96)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:106)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1131)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:433)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:408)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:240)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:406)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by davsclaus** [comment]
Does this error happens more time for you?

**Comment by davsclaus** [comment]
And do you use latest Camel idea plugin version?

**Comment by ignatov** [comment]
I don't know that the plugin version is, it's from IntelliJ Exception Analyzer system. Even more, it's quite easy to fix the problem, just check the line marker provider.

**Comment by davsclaus** [comment]
Can you point us in the direction - that documentation is not easy to find, and there are many issues on the internet reported with that error, so it is maybe a more common error in IDEA plugins. Maybe Jetbrains should make this easier for plugin developers to understand and fix.

What we are doing is this
https://github.com/davsclaus/camel-idea-plugin/blob/9dc9a9fa2d01b36129764bb18e58169cffc2bccb/camel-idea-plugin/src/main/java/org/apache/camel/idea/gutter/CamelRouteLineMarkerProvider.java#L172-L172

Not sure if there is some API from that helper to say "false" to use it because the indexer is not ready.

**Comment by davsclaus** [comment]
Found the javadoc online on github
https://github.com/JetBrains/intellij-community/blob/master/platform/core-api/src/com/intellij/openapi/project/IndexNotReadyException.java

**Comment by davsclaus** [comment]
Okay we now lazy eval the targets for the line marker so they are only fetched when you click the icon.
